"use client";
import "./globals.css";
import Navbar from "@/components/navbar";
import { addLocale, locale, PrimeReactProvider } from "primereact/api";
import { Sidebar } from "@/components/sidebar";
import { sr } from "@/lib/sr";
import { useEffect } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   addLocale("sr", sr);
  //   locale("sr");
  // }, []);

  return (
    <html lang="en">
      <PrimeReactProvider>
        <body className={`antialiased mt-24`}>
          <Navbar />
          <Sidebar />
          <main className="ml-64 p-6 overflow-auto">{children}</main>
        </body>
      </PrimeReactProvider>
    </html>
  );
}
